using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PokerStatsDataAccess
{
    public class DataAccessProvider
    {
        private PokerDBDataContext ctx = new PokerDBDataContext();

        private static DataAccessProvider _current = null;
        public static DataAccessProvider Current
        {
            get
            {
                if (_current == null)
                    _current = new DataAccessProvider();

                return _current;
            }
        }

        public enum ActionTypes 
        { 
            UserJoined = 1,
            UserLeft = 2,
            Bet = 3,
            Raise = 4,
            Check = 5,
            Fold = 6
        };

        public DataAccessProvider()
        {

        }

        public List<Game> GetActiveGames()
        {
            return ctx.Games.Where(g => g.IsActive).ToList();
        }

        public bool GameNameExists(string gameName)
        {
            return ctx.Games.Any(g => g.Name == gameName.Trim());
        }

        public int StartNewGame(string gameName, string userLogin)
        {
            User user = ctx.Users.Single(u => u.Login == userLogin);

            Game newGame = new Game()
            {
                Name  = gameName,
                IsActive = true,
                StartTime = DateTime.Now
            };

            ctx.Games.InsertOnSubmit(newGame);
            ctx.SubmitChanges();

            // ID generated by database
            int gameID = newGame.ID;

            GameAction joinAction = new GameAction()
            {
                ActionTypeID = (int)ActionTypes.UserJoined,
                GameID = gameID,
                IsCommitted = false,
                UserID = user.ID,
                Timestamp = DateTime.Now
            };

            ctx.GameActions.InsertOnSubmit(joinAction);
            ctx.SubmitChanges();

            return gameID;
        }
    }
}
